spring.application.name=discovery-service
server.port = 8761
# if we run sureka on diff port let say -> 4000 then we need to tell all service where this eureka is running by adding app.proper : eureka.client.service-url.defaultZone=http://localhost:400/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false